### ISSUE TITLE
NextJS Run Dev Issue

### ISSUE THREAD

**Issue by AngeloSenna** [IndigoProtocol/dexter#15]
Hi Team

Very excited to use this tool we are testing out the new Dexter SDK using NextJs and TypeScript, having a issue importing the lib. See Error screenshot. The code we are using is the basic setup code on the git and it seems to be erroring on line 16 when creating the Dexter object refer to Code screenshot, and also package screenshot. Error indicates files are missing not sure please advise if this is known issue or you have a quick fix. 

Error
![Screenshot 2023-06-14 082425](https://github.com/IndigoProtocol/dexter/assets/102843620/2e37035f-9ff8-4cd5-b53b-ec91586ebc04)

Code
![Screenshot 2023-06-14 082528](https://github.com/IndigoProtocol/dexter/assets/102843620/ec5f60f2-c95a-48b8-a33c-1019d669677c)

Package
![1](https://github.com/IndigoProtocol/dexter/assets/102843620/7c46ede1-b58f-4058-900e-40b3638a6a32)
![2](https://github.com/IndigoProtocol/dexter/assets/102843620/76fb50ae-0dba-4199-b4fa-253f690f529f)

**Comment by Sluder** [comment]
@AngeloSenna Thank you for reporting this! @dpbeaumont Had a similar issue, and was resolved by using babel as the project builder & adjusting the run command to use `--es-module-specifier-resolution=node`. 
I am still looking into what could be causing this issue.
Let me know if that works for you!

**Comment by NickJorens** [comment]
I'm running into the same issue.
I downgraded to node v18 from v20.

**Comment by rodrigomd94** [comment]
> EDIT: I managed to fix this issue. with the `--es-module-specifier-resolution=node`.

Can I pleas see your package.json file? I am unable to run my nextjs app with this
