### ISSUE TITLE
getLiquidityPools does not support filtering by 2 assets on VyFinance

### ISSUE THREAD

**Issue by NickJorens** [IndigoProtocol/dexter#19]
``
let pools =(await  dexter.newFetchRequest()
    .forAllDexs()
    .getLiquidityPools(djed, iusd))
 `` 

This will correctly filter for Minswap and SundaeSwap but not for VyFinance.
And no pools for Muesliswap are showing up.  (As referenced here: #17)

**Comment by dpbeaumont** [comment]
I think the all pools returned for VYFinance is covered in #12
