### ISSUE TITLE
[Bug]:  IBTC, IUSD - Input token doesn't exist in the set liquidity pool.

### ISSUE THREAD

**Issue by dpbeaumont** [IndigoProtocol/dexter#51]
### Data Provider

Blockfrost

### DEX

All

### Description

When using `withSwapInToken(asset)` assets being IBTC or IUSD, I get the following: Input token doesn't exist in the set liquidity pool.

This works for all other tokens fine.  I have checked all DEXS and the same error is raised. 
I think this could be related to how these asset share the same policyid, with different names.

Asset details:
![image](https://github.com/IndigoProtocol/dexter/assets/49551821/5f461682-14e6-43fa-8842-60decc4972c2)

Below is an image of the pool in question and the assets.
![image](https://github.com/IndigoProtocol/dexter/assets/49551821/0ea1150e-dc42-4d8c-a74a-49d547236715)

**Comment by Sluder** [comment]
@dpbeaumont Are you sure you are setting the correct liquidity pool _before_ setting the swap in token? When setting the swap in token, the swap request will ensure the token you are providing is actually in the set pool

**Comment by dpbeaumont** [comment]
> @dpbeaumont Are you sure you are setting the correct liquidity pool _before_ setting the swap in token? When setting the swap in token, the swap request will ensure the token you are providing is actually in the set pool. Even though iBTC & iUSD have the same policy ID, they are two separate pools

Yeah I did re-check and I am getting the pools using dexter. `this._request = this._dexter.newFetchRequest().onDexs([MuesliSwap.name]).forTokenPairs(assets);`

The pool returned for Muesli has the correct uuid too. As below.
![image](https://github.com/IndigoProtocol/dexter/assets/49551821/fe8e730a-fa1d-465c-bd3a-21a7bad3a4d3)

Something interesting though, just noticed this only occurs if I query token pairs of `iUSD` AND `IBTC` if I do either of these individually, the exception above doesn't occur, strange!

**Comment by dpbeaumont** [comment]
This implementation is actually working fine, it was due to how I was filtering assets to work on, by policyId, it just so happened that it was picking the first item but in the wrong order. Which is why it worked in isolation and the error was actually correct, it was just difficult to diagnose with the pools asset name hexed. 

@Sluder Thanks for the help in diagnosing this one, I'm sure this will help others who many stumble on this issue too as these assets share the name policyId but different asset name.
