### ISSUE TITLE
[Bug]: DefinitionBuilder changing Order definition

### ISSUE THREAD

**Issue by ndtr2000** [IndigoProtocol/dexter#54]
### Data Provider

Blockfrost

### DEX

All

### Description

In `loadDefinition` of DefinitionBuilder:
```typescript
public async loadDefinition(definition: DefinitionConstr): Promise<DefinitionBuilder> {
        this._definition = definition;

        return this;
    }
```
`this._definition` is referenced to the `definition` pass in to function and will be modified when we call `buildSwapOrder` for the first time. It leads to a behaviour that when you call `buildSwapOrder` second time in one dex, we receive an error on these lines (eg: minswap)
```typescript
await datumBuilder.loadDefinition(order)
            .then((builder: DefinitionBuilder) => {
                builder.pushParameters(swapParameters);
            });
```
Because the `order` definition was changed in first call (because it is a reference).
I change `this._definition = definition;` to deep copy object and it worked.

**Comment by dpbeaumont** [comment]
> ### Data Provider
> Blockfrost
> 
> ### DEX
> All
> 
> ### Description
> In `loadDefinition` of DefinitionBuilder:
> 
> ```ts
> public async loadDefinition(definition: DefinitionConstr): Promise<DefinitionBuilder> {
>         this._definition = definition;
> 
>         return this;
>     }
> ```
> 
> `this._definition` is referenced to the `definition` pass in to function and will be modified when we call `buildSwapOrder` for the first time. It leads to a behaviour that when you call `buildSwapOrder` second time in one dex, we receive an error on these lines (eg: minswap)
> 
> ```ts
> await datumBuilder.loadDefinition(order)
>             .then((builder: DefinitionBuilder) => {
>                 builder.pushParameters(swapParameters);
>             });
> ```
> 
> Because the `order` definition was changed in first call (because it is a reference). I change `this._definition = definition;` to deep copy object and it worked.

I have experienced the same error also. With same replication steps, this happens across all dex's

**Comment by Sluder** [comment]
Are we sure it has to do with a reference? For each DEX, `order` is a template for the datum, and a new `DefinitionBuilder` instance is created right above that line. So on a new call to `buildSwapOrder`, there shouldn't be anything left over from the previous call.
If you are getting a failure here, I'm wondering if that is what's causing the Tx sign error you guys were getting

**Comment by dpbeaumont** [comment]
> Are we sure it has to do with a reference? For each DEX, `order` is a template for the datum, and a new `DefinitionBuilder` instance is created right above that line. So on a new call to `buildSwapOrder`, there shouldn't be anything left over from the previous call. If you are getting a failure here, I'm wondering if that is what's causing the Tx sign error you guys were getting

Just tested this now to try and get the error in question here, on swap number 2. I get the following error. 
![image](https://github.com/IndigoProtocol/dexter/assets/49551821/66f70fc6-c412-4529-88b7-3f73c86cbed2)

**Comment by ndtr2000** [comment]
> Are we sure it has to do with a reference? For each DEX, `order` is a template for the datum, and a new `DefinitionBuilder` instance is created right above that line. So on a new call to `buildSwapOrder`, there shouldn't be anything left over from the previous call. If you are getting a failure here, I'm wondering if that is what's causing the Tx sign error you guys were getting

`order` is import once, at start of the dex file. The `pushParameters` function change it, so in the next call, tx will be failed. @dpbeaumont experienced the same problem with me. You can reproduce by create transaction from one dexter instance and one liquidity pool and submit twice.

**Comment by Sluder** [comment]
Oh! I see what you are saying now, yeah that could be it. Ill do some tests & get a fix going

**Comment by dpbeaumont** [comment]
> @ndtr2000 What you were thinking? #55 I got the error you were seeing, and updated the tests as well to catch it

Tested #55 and this works perfectly, can not replicate this issue further on second swap. Thanks @Sluder :)

**Comment by ndtr2000** [comment]
So I will close this issue as it is resolved. Thanks @Sluder
