### ISSUE TITLE
[Enhancement]:  Deno module resolution

### ISSUE THREAD

**Issue by jsyme222** [IndigoProtocol/dexter#61]
### Description

**Deno support**

The package can't be resolved within the deno ecosystem ( due to its current Node based imports - no file extension ?). 

I don't know the exact extent of what changes would need to occur in order to become fully deno compliant  but I hope this is something that others might benefit from as well.

**Comment by AlexDochioiu** [comment]
In case someone wants to do this, I wrote some small script for VESPR using regex not long ago to add .js file extension to all imports.

```
grep -rlE 'import.* "\.' src/ | xargs sed -i '' -E 's/(import.* "(\.\.?\/)+[^".]+)"/\1.js"/g'
grep -rlE 'from "\.' src/ | xargs sed -i '' -E 's/(from "(\.\.?\/)+[^".]+)"/\1.js"/g'
```

This should update all (and only) relative imports.

**Comment by jsyme222** [comment]
This issue obviously goes well beyond the Deno ecosystem as many people are struggling to use this package in any type of TS project. I am closing this as a fix that will allow this package to work in any way will in turn fix the issues with Deno.

**Comment by Sluder** [comment]
> This issue obviously goes well beyond the Deno ecosystem as many people are struggling to use this package in any type of TS project. I am closing this as a fix that will allow this package to work in any way will in turn fix the issues with Deno.

I haven't had a chance to test the package in a Deno environment (I am unfamiliar with Deno), but my comment on issue https://github.com/IndigoProtocol/dexter/issues/15 may help. 
I am also unsure what issues many people are receiving as we have not had many reports of any, but I do know quite a few people have had success. If we can gather some more info then we can start resolving those issues
