### ISSUE TITLE
[Enhancement]: Performance - Allow HTTP Keepalive Axios Opt In.

### ISSUE THREAD

**Issue by dpbeaumont** [IndigoProtocol/dexter#65]
### Description

I've been doing some testing with request performance, and have enabled `keepalive` in Axios, as a result I am seeing a significant performance improvement on request times particularly when using multiple requests in a short period of time.

Would be great if we can opt into this for Axios in the `RequestConfig`

Happy to do a PR :)

**Comment by Sluder** [comment]
Yeah PR or any documentation on what exactly you want!

**Comment by dpbeaumont** [comment]
Closing as after further testing, saw this has a negative impact on how kupo was responding intermittently causing errors. If anyone wants to investigate this further they can enable 'keepAlive' in Axios.
