### ISSUE TITLE
[Bug]: Cannot sign swapRequest

### ISSUE THREAD

**Issue by NickJorens** [IndigoProtocol/dexter#66]
### Data Provider

Kupo

### DEX

WingRiders

### Description

Hi,

I'm running into the same issue as #48  But I have enough lovelace in my wallet.

```
file:///Users/nick/code/testing/node_modules/@indigo-labs/dexter/build/providers/wallet/lucid-provider.js:95
return transaction.providerData.tx.sign().complete()
^

TypeError: transaction.providerData.tx.sign is not a function
at LucidProvider.signTransaction (file:///Users/nick/code/test/node_modules/@indigo-labs/dexter/build/providers/wallet/lucid-provider.js:95:44)
at DexTransaction.sign (file:///Users/nick/code/test/node_modules/@indigo-labs/dexter/build/dex/models/dex-transaction.js:44:37)
at Timeout._onTimeout (file:///Users/nick/code/test/build/src/index.js:248:40)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
```

Here's my build code:

```  
const swapRequest: SwapRequest = new Dexter(dexterConfig, requestConfig)
.withDataProvider(kupoProvider)
.withWalletProvider(lucidProvider)
.newSwapRequest()
.forLiquidityPool(pool)
.withSwapInToken('lovelace')
.withSwapInAmount(1_000_000n)
.withSlippagePercent(20);
const submitted = swapRequest.submit();

logger.info(TX Status: ${submitted.status});
logger.info(TX Hash ${submitted.hash});

let complete = await submitted.sign();

logger.info(`TX Status: ${submitted.status}`);
logger.info(`TX Hash ${submitted.hash}`)
```

**Comment by Sluder** [comment]
@NickJorens You dont have to call `submitted.sign()`. Once you call `submit()`, the signing & submitting is already taken care of

**Comment by NickJorens** [comment]
> @NickJorens You dont have to call `submitted.sign()`. Once you call `submit()`, the signing & submitting is already taken care of

Even when just callling that. I still don't get a tx through.

```
  const swapRequest: SwapRequest = new Dexter(dexterConfig, requestConfig)
    .withDataProvider(blockfrostProvider)
    .withWalletProvider(lucidProvider)
    .newSwapRequest()
    .forLiquidityPool(pool)
    .withSwapInToken('lovelace')
    .withSwapInAmount(1_000_000n)
    .withSlippagePercent(20);

  const submitted = swapRequest.submit();

  logger.info(`TX Status: ${submitted.status}`);
  logger.info(`TX Hash ${submitted.hash}`);
  ```
  
  It still isn't signed:
  
  ```
  {
  message: 'TX Status: 0',
  level: 'info',
  timestamp: '2023-09-12T16:39:00.835Z'
}
{
  message: 'TX Hash undefined',
  level: 'info',
  timestamp: '2023-09-12T16:39:00.835Z'
  ```

**Comment by NickJorens** [comment]
Okay, update!
I got it working, but only with Blockfrost.

```
  const lucidProvider = await new LucidProvider().loadWalletFromSeedPhrase(seedPhrase, undefined, { url: 'https://cardano-mainnet.blockfrost.io/api/v0', projectId: process.env.BLOCKFROST_KEY || '' })
  const lucidProvider = await new LucidProvider().loadWalletFromSeedPhrase(seedPhrase, undefined, {   kupoUrl: 'http://192.168.1.73:1442', ogmiosUrl: 'ws://localhost:1337' })
  ```

I can confirm that both my Kupo and Ogmios are working!
<img width="355" alt="Screenshot 2023-09-12 at 20 43 25" src="https://github.com/IndigoProtocol/dexter/assets/7328317/e1dc195a-6bc8-4ae4-a360-5ffec595b4aa">
<img width="1022" alt="Screenshot 2023-09-12 at 20 44 02" src="https://github.com/IndigoProtocol/dexter/assets/7328317/e27716c1-c724-4780-9ad6-a3927a3a6614">

**Comment by Sluder** [comment]
> Okay, update! I got it working, but only with Blockfrost. It appears there's something going on with the KupmiosConfig for Lucid?
> 
> ```
>   const lucidProvider = await new LucidProvider().loadWalletFromSeedPhrase(seedPhrase, undefined, { url: 'https://cardano-mainnet.blockfrost.io/api/v0', projectId: process.env.BLOCKFROST_KEY || '' })
>   const lucidProvider = await new LucidProvider().loadWalletFromSeedPhrase(seedPhrase, undefined, {   kupoUrl: 'http://192.168.1.73:1442', ogmiosUrl: 'ws://localhost:1337' })
> ```
> 
> I can confirm that both my Kupo and Ogmios are working! <img alt="Screenshot 2023-09-12 at 20 43 25" width="355" src="https://user-images.githubusercontent.com/7328317/267429432-e1dc195a-6bc8-4ae4-a360-5ffec595b4aa.png"> <img alt="Screenshot 2023-09-12 at 20 44 02" width="1022" src="https://user-images.githubusercontent.com/7328317/267429568-e27716c1-c724-4780-9ad6-a3927a3a6614.png">

Hmm is the tx showing up in your nodes mempool?

**Comment by Sluder** [comment]
> @Sluder How would I check this? I don't have any reference for a txhash or anything.

Ogmios has a mempool client you can use https://github.com/CardanoSolutions/ogmios. Or are you able to check if you have outgoing connections on your node? Wondering if the Tx is just stuck on your node

**Comment by NickJorens** [comment]
> Ogmios has a mempool client you can use https://github.com/CardanoSolutions/ogmios. Or are you able to check if you have outgoing connections on your node? Wondering if the Tx is just stuck on your node Also, is your `logger.info(`TX Hash ${submitted.hash}`);` never triggering?

My Ogmios instance is definitely working. I'm able to manually use Lucid and my Kupo/Ogmios instances to submit txs.
My logger is triggering but outputtin, 0 for the status and the hash is always undefined. 

I'll make a minimal reproduction of this issue and link it here.

<img width="282" alt="Screenshot 2023-09-12 at 22 44 40" src="https://github.com/IndigoProtocol/dexter/assets/7328317/66eeb77e-3740-42cd-a28a-5627e29ae712">

**Comment by Sluder** [comment]
> > Ogmios has a mempool client you can use https://github.com/CardanoSolutions/ogmios. Or are you able to check if you have outgoing connections on your node? Wondering if the Tx is just stuck on your node Also, is your `logger.info(`TX Hash ${submitted.hash}`);` never triggering?
> 
> My Ogmios instance is definitely working. I'm able to manually use Lucid and my Kupo/Ogmios instances to submit txs. My logger is triggering but outputtin, 0 for the status and the hash is always undefined.
> 
> I'll make a minimal reproduction of this issue and link it here.
> 
> <img alt="Screenshot 2023-09-12 at 22 44 40" width="282" src="https://user-images.githubusercontent.com/7328317/267459425-66eeb77e-3740-42cd-a28a-5627e29ae712.png">

Hmm what if you set your ogmiosUrl as the 192.168.1.73 IP instead of localhost? 
Ive submitted txs through dexter with ogmios, so trying to figure out what is happening here

**Comment by NickJorens** [comment]
> 

Ha sorry, that was a copy paste error. 
Check my comment here with a reproduction: https://github.com/IndigoProtocol/dexter/issues/66#issuecomment-1716405921

**Comment by Sluder** [comment]
> 

That would be a little easier actually, there are a few things I see in your repo. My Discord is `hummus2935`

**Comment by NickJorens** [comment]
Issue has been resolved.
I didn't add my address to the patterns in Kupo, so Dexter never got any utxo's it could use as inputs.
