### ISSUE TITLE
Minswap Liquidity Pool Prices & AssetB Decimal is incorrect

### ISSUE THREAD

**Issue by dpbeaumont** [IndigoProtocol/dexter#8]
When getting liquidity pools for Minswap, it appears the prices are incorrect, this could possibly be due to a precision issue, as I have noticed the assetB has lost its decimal value of 6 (I tested with token MIN which has 6 decimals). 

I can see the price calculation is using the assets decimal precision so both these issues could potentially be tied together.

Issue 1 - Liquidity pool for MIN, price shows: 8.8649.  Minswap UI Shows: 0.088649.
Issue 2 - Liquidity pool, LP Token Asset Decimals show 0, but should show 6

![image](https://github.com/IndigoProtocol/dexter/assets/49551821/e3f8a3bf-d414-464d-82b0-00381ddf8be7)

I think both of these issues could be causing other ones I have experienced, such as building a swap requests returning incorrect swapOutToken decimals, and incorrect estimatedReceive amounts.

`
const buyFromAdaPools = await request.getLiquidityPools('lovelace', new Asset(tokenDetails?.policyId ?? '', tokenDetails?.assetName ?? '', tokenDetails?.decimals));
`

**Comment by Sluder** [comment]
This issue should be fixed when https://github.com/IndigoProtocol/dexter/pull/11 goes in. The grabbing of the metadata using the default (or any metadata provider) wasn't mapping correctly
